import type { BootConfig } from '../../types'
import type { GeneratedFile } from './types'

export function generateCommonFiles(config: BootConfig): GeneratedFile[] {
  return [
    {
      path: 'AGENTS.md',
      content: generateAgentsMd(config),
    },
    ...generateProjectDotOpencode(config),
    {
      path: '.opencode/skills/configurator-validator.md',
      content: generateValidatorSkill(),
    },
    {
      path: '.gitignore',
      content: generateGitignore(),
    },
    {
      path: 'README.md',
      content: generateReadme(config),
    },
    {
      path: '.prettierrc',
      content: generatePrettierrc(),
    },
    {
      path: 'eslint.config.mjs',
      content: generateEslintConfig(),
    },
    {
      path: 'tsconfig.json',
      content: generateTsconfig(),
    },
    {
      path: '.env.example',
      content: generateEnvExample(config),
    },
    {
      path: 'docs/ARCHITECTURE.md',
      content: generateArchitectureDoc(config),
    },
  ]
}

export function generateProjectDotOpencode(
  config: BootConfig,
): GeneratedFile[] {
  return [
    {
      path: '.opencode/AGENTS.md',
      content: `## Project Overview
${config.projectName} — ${config.projectDescription || 'No description provided'}

Tech stack and architecture choices are documented in the root AGENTS.md.

## First-Time Setup

1. Run \`npm install\` to install dependencies
2. Set up environment variables (see .env.example)
3. Run \`npm run dev\` to start development
4. When ready, run \`npm run cleanup\` to remove setup scaffolding
`,
    },
    {
      path: '.opencode/PROJECT.md',
      content: `# Project Context — ${config.projectName}

## Description
${config.projectDescription || 'No description provided'}

## Tech Stack
- Framework: ${frameworkLabel(config.framework)}
- Database: ${config.database} (${config.databaseProvider})
- Auth: ${config.auth}
- Hosting: ${config.hosting}
- Target Markets: ${config.targetMarkets.join(', ')}

## Key Features
${buildFeaturesList(config) || 'None configured'}

## Available Scripts
| Command | Description |
|---------|-------------|
| npm run dev | Start dev server |
| npm run build | Production build |
| npm run typecheck | TypeScript type check |
| npm run lint | Lint source files |
| npm run format | Format with Prettier |
`,
    },
  ]
}

function generateAgentsMd(config: BootConfig): string {
  const hasCompliance = config.targetMarkets.length > 0

  const securitySkills: string[] = []
  if (config.payments !== 'none') {
    securitySkills.push(
      '- security-and-hardening: For payment and data-handling code',
    )
  }
  if (config.targetMarkets.some((m) => ['eu', 'uk'].includes(m))) {
    securitySkills.push(
      '- security-and-hardening: For GDPR-sensitive data handling',
    )
  }
  if (securitySkills.length === 0) {
    securitySkills.push(
      '- security-and-hardening: For auth, payment, and data-handling code',
    )
  }

  const complianceSection = hasCompliance
    ? `### Compliance-First Architecture

This project enforces a compliance-first approach:

1. **Compliance is automatic, not optional.** Privacy regulations, security headers, access controls, and data protection measures are auto-generated based on configuration.
2. **Cookie consent is trigger-based.** Generated only when tracking level > minimal AND target markets require it.
3. **Optimal defaults, flexible override.** Security-related options default to the strongest reasonable setting.
4. **Constraint warnings during transitions.** Track timing-sensitive constraints separately from logic errors.
5. **The compliance audit at generation time is the source of truth.`
    : `### Compliance-First Architecture

This project is built with a compliance-aware foundation:

1. **Security-first defaults.** All security-related options default to the strongest reasonable setting.
2. **Constraint validation.** Configuration consistency is validated at every step.
3. **The compliance audit at generation time is the source of truth.`

  return `# AGENTS.md

## Project Overview
${config.projectName}${config.projectDescription ? ` — ${config.projectDescription}` : ''} — generated by the Project Bootstrapper. A full-stack TypeScript application built with ${frameworkLabel(config.framework)}.

## Tool-First Philosophy

This project prioritizes tools, scripts, and pure logic over agentic work. Agents are expensive in tokens and slow to iterate. Use them only where they add unique value.

| Task | Use | Why |
|------|-----|-----|
| Type checking | npm run typecheck | Compiler — 0 tokens |
| Linting | npm run lint | Linter — 0 tokens |
| Formatting | npm run format | Formatter — 0 tokens |
| Build verification | npm run build | Bundler — 0 tokens |
| Spec writing | Agent (spec-driven-development) | Requires reasoning |
| Architectural decisions | Agent (doubt-driven-development) | Requires judgment |
| Code review | Agent (code-review-and-quality) | Requires multi-axis analysis |
| Debugging | Agent (debugging-and-error-recovery) | Requires hypothesis testing |
| Design/polish | Agent (impeccable) | Requires taste |

**Rule of thumb**: If a script can do it, write a script. Only invoke an agent when the task requires reasoning, judgment, or creative decision-making.

### Agent Invocation Policy

1. Try a script first. Is there a tool that can do this?
2. Try pure logic. Is this a simple computation?
3. Use an agent. Only if #1 and #2 don't apply.
4. Load the right skill. Always invoke the relevant skill before starting agent work.
5. Return to tools. Agent output should feed back into scripts for verification.

## Directory Structure (Co-Location)

\`\`\`
src/
├── app/                    # Next.js App Router — route segments only
│   ├── layout.tsx          # Root layout (ThemeProvider, fonts, metadata)
│   ├── globals.css         # Reset + base styles only (no component CSS)
│   ├── _components/        # Private components (underscore = not a route)
│   └── page.tsx            # Route entry (thin — re-exports feature)
├── features/               # Feature modules — self-contained
│   └── {feature}/
│       ├── types.ts        # Feature-specific types
│       ├── constraints.ts  # Validation / business logic
│       ├── {feature}.tsx   # Main component (orchestrator)
│       ├── {feature}.module.css  # Co-located styles
│       ├── compliance/     # Sub-domain of the feature
│       ├── steps/          # Sub-components used by the feature
│       └── use-{feature}.ts  # Custom hook (state management)
└── lib/                    # Shared utilities
    ├── db.ts               # Database client
    ├── auth.ts             # Auth configuration
    └── utils.ts            # Common helpers
\`\`\`

**Rules:**
1. Every feature lives in src/features/{feature-name}/ — self-contained, no cross-feature coupling
2. Step/sub-components go in {feature}/steps/ — one component per file, thin wrappers
3. Business logic extracted into hooks (use-{feature}.ts) — components only render
4. Route entry (app/page.tsx) MUST be a single re-export line — never inline a page component
5. CSS modules co-located with their component — never a global stylesheet per feature
6. Never dump all components in a single folder — sub-folders for logical groups
7. No index.ts barrel files in step folders — import directly from the file

## Development Rules

${complianceSection}

### Core Rules

1. Always use azimuth-ui components — never write raw \`<button>\`, \`<input>\`, \`<p>\`, \`<h1>\` etc.
2. All UI must use ThemeProvider tokens (--azimuth-* CSS variables)
3. Every component must be accessible (WCAG 2.2 AA)
4. Use the incremental-implementation skill for all multi-file changes
5. Use subagents for any work block that can run independently

### Code Style

- No comments unless explaining non-obvious business logic
- Three similar lines beat a premature abstraction. Use the concrete pattern three times before extracting.
- Use azimuth-ui's Text component for all typography (size, weight, color props)
- Use azimuth-ui's Button for all buttons (variant, size props)
- CSS modules for feature-specific layout; globals.css only for reset and base
- Component files named for what they render (not index.tsx)
- Props interfaces co-located with their component (not in a separate types file unless shared)

### Quality Gates (Must Pass Before Merge)

1. TypeScript: npm run typecheck — zero errors
2. Build: npm run build — must succeed
3. Lint: npm run lint — zero warnings
4. Format: npm run format — all files formatted
5. Tests: npm test — all passing
6. A11y: New UI passes WCAG 2.2 AA check${config.hasPublicApi ? '\n7. API: OpenAPI spec matches implementation — no drift' : ''}

### Must-Use Skills

- full-audit: Run before releases, after major changes, or on request
- a11y-audit: After any UI change, audit for WCAG 2.2 AA compliance
${securitySkills.join('\n')}
- impeccable: For any UI design or styling decisions. All interfaces must pass impeccable standards.
- spec-driven-development: BEFORE implementing any new feature
- test-driven-development: For any logic code. Write tests first
- code-review-and-quality: Before merging any change
- incremental-implementation: For any change touching multiple files
- doubt-driven-development: For compliance and security-sensitive code

### Anti-Patterns

- DO NOT write raw HTML elements — use azimuth components
- DO NOT invent new color tokens — use --azimuth-color-* variables
- DO NOT skip compliance auditing for any configurator change
- DO NOT merge without code-review-and-quality first
- DO NOT create mega-components — split into step/sub components after ~100 lines
- DO NOT put business logic in components — extract into hooks
- DO NOT use barrel index.ts files in sub-folders — import from the source file

${generateProjectContext(config)}
`
}

function generateProjectContext(config: BootConfig): string {
  const sections: string[] = []

  sections.push(`## Project Context

Generated for: ${config.projectName}
Framework: ${config.framework}
Hosting: ${config.hosting}
Database: ${config.database} (${config.databaseProvider})
Auth: ${config.auth}
Target Markets: ${config.targetMarkets.join(', ')}
`)

  // Schema tables
  const tables: string[] = []
  if (config.auditLogging) tables.push('audit_logs')
  if (config.apiKeyAuth) tables.push('api_keys')
  if (config.appointments) tables.push('appointments')
  if (config.eSignature) tables.push('documents', 'signatures')
  if (config.auth !== 'none') tables.push('sessions')
  if (config.payments !== 'none') tables.push('payments')
  if (tables.length > 0) {
    sections.push(`### Database Tables
- users (core user accounts)
${tables.map((t) => `- ${t}`).join('\n')}
`)
  }

  // API routes
  const apiRoutes: string[] = []
  if (config.payments === 'stripe')
    apiRoutes.push('POST /api/stripe — Stripe webhook handler')
  if (config.appointments)
    apiRoutes.push('GET/POST /api/appointments — Manage appointments')
  if (config.eSignature)
    apiRoutes.push('GET/POST /api/documents — Document management')
  if (config.apiKeyAuth)
    apiRoutes.push('GET/POST /api/admin/api-keys — API key management')
  if (config.inAppNotifications)
    apiRoutes.push('GET/POST /api/notifications — In-app notifications')
  if (config.uptimeMonitoring) apiRoutes.push('GET /api/health — Health check')
  if (config.dataExport) apiRoutes.push('GET /api/export — Data export')
  if (config.auditLogging)
    apiRoutes.push('GET /api/compliance/data-access — DSAR access endpoint')
  if (config.auditLogging)
    apiRoutes.push(
      'POST /api/compliance/data-deletion — DSAR deletion endpoint',
    )
  if (config.auditLogging)
    apiRoutes.push(
      'POST /api/compliance/data-correction — DSAR correction endpoint',
    )
  if (config.hasCrudEndpoints)
    apiRoutes.push('GET/POST /api/crud/:entity — Generic CRUD scaffold')
  if (apiRoutes.length > 0) {
    sections.push(`### API Routes
${apiRoutes.map((r) => `- ${r}`).join('\n')}
`)
  }

  // Env var summary
  sections.push(`### Required Environment Variables
See \`.env.example\` for the full list. Key variables to set:\n- Database: NEXT_PUBLIC_SUPABASE_URL, NEXT_PUBLIC_SUPABASE_ANON_KEY${config.payments === 'stripe' ? '\n- Payments: STRIPE_SECRET_KEY, NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY' : ''}${config.emailProvider !== 'none' ? '\n- Email: RESEND_API_KEY (or equivalent)' : ''}${config.monitoring === 'sentry' ? '\n- Monitoring: NEXT_PUBLIC_SENTRY_DSN, SENTRY_AUTH_TOKEN' : ''}${config.communicationPlatforms.includes('slack') ? '\n- Slack: SLACK_BOT_TOKEN, SLACK_SIGNING_SECRET' : ''}${config.logManagement === 'axiom' ? '\n- Logging: AXIOM_API_TOKEN, NEXT_PUBLIC_AXIOM_DATASET' : ''}
`)

  // Compliance note
  if (config.targetMarkets.length > 0) {
    sections.push(`### Compliance
Applicable regulations for selected markets (${config.targetMarkets.join(', ')}):
- See docs/COMPLIANCE.md and docs/PRIVACY.md for full details
- DSAR endpoints are available at /api/compliance/* for data access/deletion/correction requests
`)
  }

  return sections.join('\n').trim()
}

function generateValidatorSkill(): string {
  return `---
name: configurator-validator
description: Validates the current configuration against engineering constraints. Use when checking config compatibility.
---

# Configurator Validator

Ensures the project configuration is internally consistent and production-ready.

## Usage (CLI Script)

\`\`\`bash
npx tsx scripts/validate-config.ts --config .tmp/config.json
cat .tmp/config.json | npx tsx scripts/validate-config.ts --stdin
npx tsx scripts/validate-config.ts --config .tmp/config.json --json
\`\`\`

## When to Invoke the Agent

Only invoke agent reasoning when:
- A constraint violation needs contextual explanation
- Multiple constraints interact and a tradeoff decision is needed
- The user needs a recommendation, not just a violation list
`
}

function generateGitignore(): string {
  return `node_modules/
.env
.env.local
.env.*.local
.next/
dist/
*.tsbuildinfo
.tmp/
coverage/
`
}

function getEnvVarDescriptions(config: BootConfig): Record<string, string> {
  const vars: Record<string, string> = {}

  vars['NEXT_PUBLIC_SUPABASE_URL'] = 'Supabase project URL'
  vars['NEXT_PUBLIC_SUPABASE_ANON_KEY'] =
    'Supabase anonymous key (safe for client)'
  vars['SUPABASE_SERVICE_ROLE_KEY'] = 'Supabase service role key (server-only)'

  switch (config.databaseProvider) {
    case 'supabase':
      vars['DATABASE_URL'] = 'PostgreSQL connection string (Supabase managed)'
      break
    case 'planetscale':
      vars['DATABASE_URL'] = 'MySQL connection string (PlanetScale managed)'
      break
    case 'turso':
      vars['DATABASE_URL'] = 'libSQL/Turso database URL'
      vars['TURSO_AUTH_TOKEN'] = 'Turso authentication token'
      break
    case 'neon':
      vars['DATABASE_URL'] = 'PostgreSQL connection string (Neon serverless)'
      break
    case 'atlas':
      vars['MONGODB_URI'] = 'MongoDB Atlas connection string'
      break
    default:
      vars['DATABASE_URL'] = 'Database connection string'
  }

  switch (config.auth) {
    case 'jwt':
      vars['JWT_SECRET'] = 'Secret key for signing JWTs'
      break
    case 'next-auth':
      vars['AUTH_SECRET'] = 'Auth.js secret for encrypting sessions'
      vars['AUTH_URL'] = 'Base URL of the application'
      if (config.ssoProviders.includes('google')) {
        vars['GOOGLE_CLIENT_ID'] = 'Google OAuth client ID'
        vars['GOOGLE_CLIENT_SECRET'] = 'Google OAuth client secret'
      }
      if (config.ssoProviders.includes('github')) {
        vars['GITHUB_CLIENT_ID'] = 'GitHub OAuth client ID'
        vars['GITHUB_CLIENT_SECRET'] = 'GitHub OAuth client secret'
      }
      if (config.ssoProviders.includes('microsoft')) {
        vars['AZURE_AD_CLIENT_ID'] = 'Azure AD application client ID'
        vars['AZURE_AD_CLIENT_SECRET'] = 'Azure AD application client secret'
        vars['AZURE_AD_TENANT_ID'] = 'Azure AD tenant ID'
      }
      if (config.ssoProviders.includes('apple')) {
        vars['APPLE_CLIENT_ID'] = 'Apple Sign In service ID'
        vars['APPLE_CLIENT_SECRET'] = 'Apple Sign In private key'
      }
      break
    case 'auth0':
      vars['AUTH0_SECRET'] = 'Auth0 secret for encrypting sessions'
      vars['AUTH0_ISSUER_BASE_URL'] = 'Auth0 tenant domain URL'
      vars['AUTH0_BASE_URL'] = 'Base URL of the application'
      vars['AUTH0_CLIENT_ID'] = 'Auth0 application client ID'
      vars['AUTH0_CLIENT_SECRET'] = 'Auth0 application client secret'
      break
  }

  if (config.payments === 'stripe') {
    vars['STRIPE_SECRET_KEY'] = 'Stripe secret key (server-only)'
    vars['STRIPE_WEBHOOK_SECRET'] = 'Stripe webhook signing secret'
    vars['NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY'] =
      'Stripe publishable key (safe for client)'
  }

  if (config.emailProvider === 'resend') {
    vars['RESEND_API_KEY'] = 'Resend API key'
    vars['EMAIL_FROM'] = 'From address for transactional emails'
  }

  if (config.monitoring === 'sentry') {
    vars['NEXT_PUBLIC_SENTRY_DSN'] = 'Sentry DSN for client-side error tracking'
    vars['SENTRY_AUTH_TOKEN'] = 'Sentry auth token for sourcemap uploads'
    vars['SENTRY_ORG'] = 'Sentry organisation slug'
    vars['SENTRY_PROJECT'] = 'Sentry project slug'
  }

  if (config.communicationPlatforms.includes('slack')) {
    vars['SLACK_BOT_TOKEN'] = 'Slack bot token for messaging'
    vars['SLACK_SIGNING_SECRET'] = 'Slack signing secret for verifying requests'
  }

  if (config.logManagement === 'axiom') {
    vars['NEXT_PUBLIC_AXIOM_DATASET'] = 'Axiom dataset name for log ingestion'
    vars['AXIOM_API_TOKEN'] = 'Axiom API token for sending logs'
  }

  if (config.corsEnabled) {
    vars['CORS_ORIGINS'] = 'Allowed CORS origins (comma-separated, * for all)'
  }

  if (config.smsProvider === 'twilio') {
    vars['TWILIO_ACCOUNT_SID'] = 'Twilio account SID'
    vars['TWILIO_AUTH_TOKEN'] = 'Twilio auth token'
    vars['TWILIO_PHONE_NUMBER'] = 'Twilio phone number for sending SMS'
  }

  if (config.rateLimiting === 'upstash') {
    vars['UPSTASH_REDIS_URL'] = 'Upstash Redis URL for rate limiting'
    vars['UPSTASH_REDIS_TOKEN'] = 'Upstash Redis token for rate limiting'
  }

  return vars
}

function buildFeaturesList(config: BootConfig): string {
  const items: string[] = []
  if (config.auth !== 'none') {
    let authDesc = `- **Authentication** — ${config.auth}`
    if (config.totpEnabled) authDesc += ' with TOTP/2FA'
    if (config.passkeysEnabled) authDesc += ' + Passkeys'
    items.push(authDesc)
  }
  if (config.payments !== 'none')
    items.push(`- **Payments** — ${config.payments}`)
  if (config.fileStorage !== 'none')
    items.push(`- **File Storage** — ${config.fileStorage}`)
  if (config.emailProvider !== 'none')
    items.push(`- **Email** — ${config.emailProvider}`)
  if (config.monitoring !== 'none')
    items.push(`- **Monitoring** — ${config.monitoring}`)
  if (config.communicationPlatforms.length > 0)
    items.push(
      `- **Integrations** — ${config.communicationPlatforms.join(', ')}`,
    )
  if (config.featureFlags) items.push('- **Feature Flags**')
  if (config.auditLogging) items.push('- **Audit Logging**')
  return items.join('\n')
}

function generateReadme(config: BootConfig): string {
  const features = buildFeaturesList(config)
  const envRows = Object.entries(getEnvVarDescriptions(config))
    .map(([k, v]) => `| ${k} | ${v} |`)
    .join('\n')

  return `# ${config.projectName}

Generated by the Project Bootstrapper.

## Tech Stack
- Framework: ${frameworkLabel(config.framework)}
- Database: ${config.database}${config.databaseProvider !== 'self-hosted' ? ` (${config.databaseProvider})` : ''}
- Auth: ${config.auth}
- Hosting: ${config.hosting}

${features ? `## Configured Features\n\n${features}\n` : ''}
## Getting Started

\`\`\`bash
npm install
npm run dev
\`\`\`

## Scripts

| Command | Description |
|---------|-------------|
| npm run dev | Start development server |
| npm run build | Production build |
| npm run typecheck | TypeScript type checking |
| npm run lint | Lint all source files |
| npm run format | Format with Prettier |

## Environment Variables

| Variable | Description |
|----------|-------------|
${envRows}

See \`.env.example\` for the full list.

## Quality Gates

Before submitting a PR, ensure these pass:
- \`npm run typecheck\` — zero errors
- \`npm run lint\` — zero warnings
- \`npm run build\` — succeeds

## Architecture

See [docs/ARCHITECTURE.md](docs/ARCHITECTURE.md) for architecture overview.

### Compliance Docs

- [COMPLIANCE.md](docs/COMPLIANCE.md) — Regulatory requirements for your target markets
- [SECURITY.md](docs/SECURITY.md) — Security hardening checklist
- [PRIVACY.md](docs/PRIVACY.md) — Privacy policy
- [DATA_RETENTION.md](docs/DATA_RETENTION.md) — Data retention schedule
`
}

function generatePrettierrc(): string {
  return (
    JSON.stringify(
      {
        semi: false,
        singleQuote: true,
        trailingComma: 'all',
        printWidth: 100,
        tabWidth: 2,
      },
      null,
      2,
    ) + '\n'
  )
}

function generateEslintConfig(): string {
  return `import js from '@eslint/js'
import tseslint from 'typescript-eslint'

export default tseslint.config(
  { ignores: ['node_modules/', '.next/', 'dist/', '.tmp/', 'coverage/'] },
  js.configs.recommended,
  ...tseslint.configs.recommended,
)
`
}

function generateTsconfig(): string {
  return (
    JSON.stringify(
      {
        compilerOptions: {
          target: 'ES2017',
          lib: ['dom', 'dom.iterable', 'esnext'],
          allowJs: true,
          skipLibCheck: true,
          strict: true,
          noEmit: true,
          esModuleInterop: true,
          module: 'esnext',
          moduleResolution: 'bundler',
          resolveJsonModule: true,
          isolatedModules: true,
          jsx: 'preserve',
          incremental: true,
          paths: {
            '@/*': ['./src/*', './*'],
          },
        },
        include: [
          'next-env.d.ts',
          '**/*.ts',
          '**/*.tsx',
          '.next/types/**/*.ts',
        ],
        exclude: ['node_modules'],
      },
      null,
      2,
    ) + '\n'
  )
}

function frameworkLabel(framework: BootConfig['framework']): string {
  const labels: Record<typeof framework, string> = {
    nextjs: 'Next.js 15 (App Router)',
    'vite-react': 'Vite + React 19',
    remix: 'Remix',
    astro: 'Astro',
  }
  return labels[framework]
}

function generateEnvExample(config: BootConfig): string {
  const lines: string[] = []

  lines.push(
    '# Supabase',
    'NEXT_PUBLIC_SUPABASE_URL=',
    'NEXT_PUBLIC_SUPABASE_ANON_KEY=',
    'SUPABASE_SERVICE_ROLE_KEY=  # Server-only — never expose to client',
  )

  switch (config.databaseProvider) {
    case 'supabase':
      lines.push(
        'DATABASE_URL=postgresql://postgres:[PASSWORD]@db.[PROJECT_REF].supabase.co:5432/postgres',
      )
      break
    case 'planetscale':
      lines.push(
        'DATABASE_URL=mysql://[USERNAME]:[PASSWORD]@[HOST]/[DATABASE]?ssl=%7B%22rejectUnauthorized%22%3Atrue%7D',
      )
      break
    case 'turso':
      lines.push('DATABASE_URL=libsql://[DATABASE]-[ORGANIZATION].turso.io')
      lines.push('TURSO_AUTH_TOKEN=')
      break
    case 'neon':
      lines.push(
        'DATABASE_URL=postgresql://[USERNAME]:[PASSWORD]@[HOST]/[DATABASE]?sslmode=require',
      )
      break
    case 'atlas':
      lines.push(
        'MONGODB_URI=mongodb+srv://[USERNAME]:[PASSWORD]@[CLUSTER].mongodb.net/[DATABASE]?retryWrites=true&w=majority',
      )
      break
    default:
      break
  }
  lines.push('')

  switch (config.auth) {
    case 'jwt':
      lines.push('', 'JWT_SECRET=your-secret-at-least-32-chars')
      break
    case 'next-auth': {
      lines.push(
        '',
        'AUTH_SECRET=your-auth-secret',
        'AUTH_URL=http://localhost:3000',
      )
      for (const p of config.ssoProviders) {
        switch (p) {
          case 'google':
            lines.push('GOOGLE_CLIENT_ID=', 'GOOGLE_CLIENT_SECRET=')
            break
          case 'github':
            lines.push('GITHUB_CLIENT_ID=', 'GITHUB_CLIENT_SECRET=')
            break
          case 'microsoft':
            lines.push(
              'AZURE_AD_CLIENT_ID=',
              'AZURE_AD_CLIENT_SECRET=',
              'AZURE_AD_TENANT_ID=',
            )
            break
          case 'apple':
            lines.push('APPLE_CLIENT_ID=', 'APPLE_CLIENT_SECRET=')
            break
        }
      }
      break
    }
    case 'auth0':
      lines.push(
        '',
        'AUTH0_SECRET=long-random-secret',
        'AUTH0_ISSUER_BASE_URL=https://[tenant].auth0.com',
        'AUTH0_BASE_URL=http://localhost:3000',
        'AUTH0_CLIENT_ID=',
        'AUTH0_CLIENT_SECRET=',
      )
      break
  }

  if (config.payments === 'stripe') {
    lines.push(
      '',
      '# Stripe',
      'STRIPE_SECRET_KEY=sk_live_',
      'STRIPE_WEBHOOK_SECRET=whsec_',
      'NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_',
    )
  }

  if (config.emailProvider === 'resend') {
    lines.push(
      '',
      '# Email (Resend)',
      'RESEND_API_KEY=re_',
      `EMAIL_FROM=hello@${config.projectName}.com`,
    )
  }

  if (config.smsProvider === 'twilio') {
    lines.push(
      '',
      '# Twilio',
      'TWILIO_ACCOUNT_SID=',
      'TWILIO_AUTH_TOKEN=',
      'TWILIO_PHONE_NUMBER=',
    )
  }

  if (config.monitoring === 'sentry') {
    lines.push(
      '',
      '# Sentry',
      'NEXT_PUBLIC_SENTRY_DSN=',
      'SENTRY_AUTH_TOKEN=',
      'SENTRY_ORG=',
      'SENTRY_PROJECT=',
    )
  }

  if (config.communicationPlatforms.includes('slack')) {
    lines.push('', '# Slack', 'SLACK_BOT_TOKEN=xoxb-', 'SLACK_SIGNING_SECRET=')
  }

  if (config.logManagement === 'axiom') {
    lines.push('', '# Axiom', 'NEXT_PUBLIC_AXIOM_DATASET=', 'AXIOM_API_TOKEN=')
  }

  if (config.corsEnabled) {
    lines.push('', '# CORS', 'CORS_ORIGINS=http://localhost:3000')
  }

  if (config.rateLimiting === 'upstash' || config.cache === 'upstash-redis') {
    lines.push(
      '',
      '# Upstash Redis',
      'UPSTASH_REDIS_URL=',
      'UPSTASH_REDIS_TOKEN=',
    )
  }

  return lines.join('\n')
}

export function generateAppConfig(config: BootConfig): GeneratedFile[] {
  return [
    {
      path: 'lib/navigation.ts',
      content: `export interface NavPage {
  label: string;
  path: string;
  icon?: string;
}

export const APP_CONFIG = {
  title: ${JSON.stringify(config.appTitle)},
  logo: ${JSON.stringify(config.appLogo)},
  navStyle: ${JSON.stringify(config.navStyle)},
};

export const NAV_PAGES: NavPage[] = ${JSON.stringify(config.navPages, null, 2)} as const;
`,
    },
    {
      path: 'src/app/setup/page.tsx',
      content: `"use client";

import { Container, Text, Button, Card, Stack, Alert } from "azimuth-ui";
import type { NavPage } from "@/lib/navigation";
import { NAV_PAGES, APP_CONFIG } from "@/lib/navigation";

export default function SetupPage() {
  return (
    <Container style={{ maxWidth: 640, margin: "4rem auto" }}>
      <Stack spacing="md">
        <Text element={{ as: "h1", size: "h1" }} weight="bold">{APP_CONFIG.title} — Setup</Text>
        <Text color="secondary">Follow the steps below to configure your application.</Text>

        <Card>
          <Stack spacing="md">
            <Text weight="semibold">Navigation Pages</Text>
            {NAV_PAGES.length > 0 ? (
              <ul>
                {NAV_PAGES.map((page, i) => (
                  <li key={i}>
                    <Text element={{ size: "sm" }}>{page.label} → {page.path}</Text>
                  </li>
                ))}
              </ul>
            ) : (
              <Text element={{ size: "sm" }} color="muted">No pages configured yet.</Text>
            )}
          </Stack>
        </Card>

        <Alert variant="info" title="Getting Started">
          Check docs/DEPLOYMENT.md for service-by-service setup instructions.
        </Alert>
      </Stack>
    </Container>
  );
}
`,
    },
  ]
}

function generateArchitectureDoc(config: BootConfig): string {
  return `# Architecture — ${config.projectName}

This project follows the co-location pattern described in AGENTS.md.

## Tech Stack
- **Framework**: ${frameworkLabel(config.framework)}
- **Hosting**: ${config.hosting}
- **Database**: ${config.database}${config.databaseProvider !== 'self-hosted' ? ` (${config.databaseProvider})` : ''}
- **Auth**: ${config.auth}
- **Payments**: ${config.payments}
- **Monitoring**: ${config.monitoring}
- **Email**: ${config.emailProvider}${config.smsProvider !== 'none' ? `\n- **SMS**: ${config.smsProvider}` : ''}
- **File Storage**: ${config.fileStorage}
- **Cache**: ${config.cache}
- **Analytics**: ${config.analyticsProvider}

## Directory Structure

\`\`\`
src/
├── app/                    # Next.js App Router — route segments only
│   ├── layout.tsx          # Root layout (ThemeProvider, fonts, metadata)
│   ├── globals.css         # Reset + base styles
│   └── page.tsx            # Home page
├── features/               # Feature modules — self-contained
│   └── {feature}/
│       ├── types.ts        # Feature-specific types
│       ├── {feature}.tsx   # Main component
│       ├── {feature}.module.css  # Co-located styles
│       └── use-{feature}.ts  # Custom hook
└── lib/                    # Shared utilities
    ├── db.ts               # Database client
    ├── auth.ts             # Auth configuration
    └── utils.ts            # Common helpers
\`\`\`

## API Routes
${config.apiStyle !== 'none' ? `- **Style**: ${config.apiStyle}\n${config.hasPublicApi ? '- Public API endpoints under `/api/`\n' : ''}${config.hasWebhooks ? '- Webhook endpoints under `/api/webhooks/`\n' : ''}` : '- No API routes configured'}

## Authentication Flow
${
  config.auth !== 'none'
    ? `Authentication is handled by ${config.auth}${config.totpEnabled ? ' with TOTP/2FA enforcement' : ''}${config.passkeysEnabled ? ' and Passkey support' : ''}.
${config.ssoProviders.length > 0 ? `SSO providers: ${config.ssoProviders.join(', ')}.\n` : ''}
The middleware in \`middleware.ts\` protects all routes except those listed in the public paths matcher.`
    : 'No authentication configured. All routes are public.'
}

## Data Model
- **Database**: ${config.database} on ${config.databaseProvider}
${config.multiTenancy !== 'none' ? `- **Multi-tenancy**: ${config.multiTenancy === 'shared' ? 'Row-level security (shared database)' : 'Database-per-tenant (isolated)'}\n` : ''}${config.search !== 'none' ? `- **Search**: ${config.search}\n` : ''}
`
}
