import type { BootConfig } from '../../types'
import type { GeneratedFile } from './types'
import { buildServices } from './setup-wizard'

export function generateSetupCli(config: BootConfig): GeneratedFile[] {
  const services = buildServices(config)
  const servicesJson = JSON.stringify(services, null, 2)

  return [
    {
      path: 'scripts/setup.ts',
      content: `#!/usr/bin/env node
/**
 * Setup script — walks through each service configuration step-by-step.
 * Run: npx tsx scripts/setup.ts
 */

import * as fs from "node:fs";
import * as path from "node:path";
import * as readline from "node:readline";

type ServiceField = { key: string; label: string; docLink?: string };
type Service = {
  name: string;
  url: string;
  description: string;
  fields: ServiceField[];
};

const REQUIRED_SERVICES: Service[] = ${servicesJson};

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});

function prompt(query: string): Promise<string> {
  return new Promise((resolve) => rl.question(query, resolve));
}

async function main() {
  // Ensure dependencies are installed before configuring
  if (!fs.existsSync(path.join(process.cwd(), "node_modules"))) {
    console.log("📦 Installing dependencies...");
    const { execSync } = await import("node:child_process");
    execSync("npm install", { stdio: "inherit" });
    console.log("");
  }

  console.log("\\n═══════════════════════════════════════════════");
  console.log("  ${config.projectName} — Setup Wizard");
  console.log("═══════════════════════════════════════════════");
  console.log("");
  console.log("This will guide you through configuring each service.");
  console.log("Press Enter to skip a field (leave it empty).\\n");

  const envPath = path.join(process.cwd(), ".env.local");
  const existing: Record<string, string> = {};
  if (fs.existsSync(envPath)) {
    const content = fs.readFileSync(envPath, "utf-8");
    for (const line of content.split("\\n")) {
      const eqIdx = line.indexOf("=");
      if (eqIdx > 0 && !line.startsWith("#")) {
        existing[line.slice(0, eqIdx).trim()] = line.slice(eqIdx + 1).trim();
      }
    }
  }

  const envEntries: string[] = [];

  for (const svc of REQUIRED_SERVICES) {
    console.log("\\n── " + svc.name + " ──");
    console.log("  " + svc.description);
    console.log("  Open: " + svc.url + "\\n");

    for (const field of svc.fields) {
      const current = existing[field.key] || "";
      const defaultStr = current ? " [" + current + "]" : "";
      const answer = await prompt("  " + field.key + defaultStr + ": ");
      const val = answer.trim() || current;
      envEntries.push(field.key + "=" + val);
    }
  }

  envEntries.sort();
  envEntries.unshift("# Generated by npm run setup\\n");

  fs.writeFileSync(envPath, envEntries.join("\\n") + "\\n");
  console.log("\\n✅ Environment variables saved to .env.local");
  console.log("Run npm run dev to start your application.\\n");

  rl.close();
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
`,
    },
  ]
}
