#!/usr/bin/env node
/**
 * Setup script — walks through each service configuration step-by-step.
 * Run: npx tsx scripts/setup.ts
 */

import * as fs from "node:fs";
import * as path from "node:path";
import * as readline from "node:readline";

type ServiceField = { key: string; label: string; docLink?: string };
type Service = {
  name: string;
  url: string;
  description: string;
  fields: ServiceField[];
};

const REQUIRED_SERVICES: Service[] = [
  {
    "name": "Supabase",
    "url": "https://supabase.com/dashboard",
    "description": "Database, auth, and file storage backend. Create a project and copy your API keys.",
    "fields": [
      {
        "key": "NEXT_PUBLIC_SUPABASE_URL",
        "label": "Project URL",
        "docLink": "https://supabase.com/dashboard/project/_/settings/api"
      },
      {
        "key": "NEXT_PUBLIC_SUPABASE_ANON_KEY",
        "label": "Anon Public Key"
      }
    ]
  },
  {
    "name": "Sentry",
    "url": "https://sentry.io/settings/account/api/",
    "description": "Error tracking and performance monitoring. Create a project and get your DSN.",
    "fields": [
      {
        "key": "NEXT_PUBLIC_SENTRY_DSN",
        "label": "DSN",
        "docLink": "https://docs.sentry.io/platforms/javascript/guides/nextjs/"
      },
      {
        "key": "SENTRY_AUTH_TOKEN",
        "label": "Auth Token"
      },
      {
        "key": "SENTRY_ORG",
        "label": "Organization Slug"
      },
      {
        "key": "SENTRY_PROJECT",
        "label": "Project Slug"
      }
    ]
  },
  {
    "name": "Slack",
    "url": "https://api.slack.com/apps",
    "description": "Messaging and notifications. Create a Slack app, install it to your workspace, and get your tokens.",
    "fields": [
      {
        "key": "SLACK_BOT_TOKEN",
        "label": "Bot Token",
        "docLink": "https://api.slack.com/apps"
      },
      {
        "key": "SLACK_SIGNING_SECRET",
        "label": "Signing Secret"
      }
    ]
  },
  {
    "name": "Vercel",
    "url": "https://vercel.com/dashboard",
    "description": "Deployment platform. Connect your GitHub repository and deploy. Environment variables should be configured in the Vercel dashboard.",
    "fields": []
  }
];

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});

function prompt(query: string): Promise<string> {
  return new Promise((resolve) => rl.question(query, resolve));
}

async function main() {
  console.log("\n═══════════════════════════════════════════════");
  console.log("  nova-mir-product — Setup Wizard");
  console.log("═══════════════════════════════════════════════");
  console.log("");
  console.log("This will guide you through configuring each service.");
  console.log("Press Enter to skip a field (leave it empty).\n");

  const envPath = path.join(process.cwd(), ".env.local");
  const existing: Record<string, string> = {};
  if (fs.existsSync(envPath)) {
    const content = fs.readFileSync(envPath, "utf-8");
    for (const line of content.split("\n")) {
      const eqIdx = line.indexOf("=");
      if (eqIdx > 0 && !line.startsWith("#")) {
        existing[line.slice(0, eqIdx).trim()] = line.slice(eqIdx + 1).trim();
      }
    }
  }

  const envEntries: string[] = [];

  for (const svc of REQUIRED_SERVICES) {
    console.log("\n── " + svc.name + " ──");
    console.log("  " + svc.description);
    console.log("  Open: " + svc.url + "\n");

    for (const field of svc.fields) {
      const current = existing[field.key] || "";
      const defaultStr = current ? " [" + current + "]" : "";
      const answer = await prompt("  " + field.key + defaultStr + ": ");
      const val = answer.trim() || current;
      envEntries.push(field.key + "=" + val);
    }
  }

  envEntries.sort();
  envEntries.unshift("# Generated by npm run setup\n");

  fs.writeFileSync(envPath, envEntries.join("\n") + "\n");
  console.log("\n✅ Environment variables saved to .env.local");
  console.log("Run npm run dev to start your application.\n");

  rl.close();
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
